name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: build app
        run: chmod +x ./gradlew buildJar
      - name: Run spring boot
        run: java -jar build/libs/Task-Tracker-0.0.1-SNAPSHOT.jar
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: build app
        run: chmod +x ./gradlew buildJar
      - name: Run spring boot
        run: java -jar build/libs/Task-Tracker-0.0.1-SNAPSHOT.jar
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  test_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: build app
        run: chmod +x ./gradlew buildJar
      - name: Run spring boot
        run: java -jar build/libs/Task-Tracker-0.0.1-SNAPSHOT.jar
      - name: Setup and execute Gradle 'test' task
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
